# Generated by Django 5.2.7 on 2025-10-25 13:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_product_category_category'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='Category',
            new_name='product',
        ),
    ]
